//===- ToyPasses.h - Toy pass declarations --------------------------------===//
//
// Public entry points for the Toy passes: the factories, the options struct,
// and the registration function an opt-style tool calls. All three are
// generated by `mlir-tblgen --gen-pass-decls` from ToyPasses.td.
//
//===----------------------------------------------------------------------------===//
#ifndef TOY_TOYPASSES_H
#define TOY_TOYPASSES_H

#include "mlir/Pass/Pass.h"

#include <memory>

#include "Toy/ToyDialect.h"                        // ::toy::ToyDialect,      named in dependentDialects
#include "mlir/Dialect/PDL/IR/PDL.h"                // ::mlir::pdl::PDLDialect,  "
#include "mlir/Dialect/PDLInterp/IR/PDLInterp.h"    // ::mlir::pdl_interp::PDLInterpDialect

namespace toy {

// Fills `patterns` with the DRR-generated rewrites (ToyPatterns.cpp).
void populateToyFoldPatterns(mlir::RewritePatternSet &patterns);

// GEN_PASS_DECL expands to, for every pass in the group:
//   struct ToyFoldOptions { int64_t maxIterations = 10; };
//   std::unique_ptr<::mlir::Pass> createToyFold();
//   std::unique_ptr<::mlir::Pass> createToyFold(ToyFoldOptions options);
#define GEN_PASS_DECL
#include "Toy/ToyPasses.h.inc"

// GEN_PASS_REGISTRATION expands to registerToyFold() and the group-wide
// registerToyPasses(), which an opt tool calls once at startup.
#define GEN_PASS_REGISTRATION
#include "Toy/ToyPasses.h.inc"

} // namespace toy

#endif // TOY_TOYPASSES_H
