#ifndef HELLO_HELLODIALECT_H
#define HELLO_HELLODIALECT_H
#include "mlir/IR/Dialect.h"
// Generated by add_mlir_dialect(HelloOps hello): <td>Dialect.h.inc
#include "Hello/HelloOpsDialect.h.inc"
#endif
